version: '3.3'
services:
  #https://github.com/cer/microservices-examples/blob/master/docker-compose.yml
  grafana:
    image: grafana/grafana:5.4.2
    ports:
      - "3000:3000"
    depends_on:
      - prom
  prom:
    image: prom/prometheus:v2.6.0
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    depends_on:
      - course

  course-mysql:
    image: mysql:8.0.19
    # volumes:
    #     - ~/volumes/jhipster/y/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: micro_course
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
    restart: unless-stopped
    ports:
      - target: 3306
        published: 33062
        protocol: tcp
        mode: host
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  user-mysql:
    image: mysql:8.0.19
    # volumes:
    #     - ~/volumes/jhipster/y/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: micro_user
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
    restart: unless-stopped
    ports:
      - target: 3306
        published: 33063
        protocol: tcp
        mode: host
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  eureka:
    image: "microservice/discovery"
    ports:
      - target: 8761
        published: 9001
        protocol: tcp
        mode: host
    restart: unless-stopped
    #healthcheck:
      #test: ["CMD", "curl", "--fail", "--silent", "localhost:8761/actuator/health 2>&1 | grep UP || exit 1"]
      #interval: 10s
      #timeout: 2s
      #retries: 10
  course:
    image: "microservice/course"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=default
      # - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      #- SPRING_DATASOURCE_URL=jdbc:mysql://course-mysql:3306/micro_course?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=true
      #- SPRING_DATASOURCE_USERNAME=root
      #- SPRING_DATASOURCE_PASSWORD=root
      #- EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    #ports:
     # - target: 8001
     #   published: 8001
     #   protocol: tcp
      #  mode: host
    links:
      - "eureka:eureka"
      - "course-mysql:course-mysql"
    depends_on:
      - "eureka"
      - "course-mysql"
  user:
    image: "microservice/user"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=default
      # - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      #- SPRING_DATASOURCE_URL=jdbc:mysql://user-mysql:3306/micro_user?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=true
      #- SPRING_DATASOURCE_USERNAME=root
      #- SPRING_DATASOURCE_PASSWORD=root
      #- EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    #ports:
      #- target: 8000
      #  published: 8000
      #  protocol: tcp
      #  mode: host
    links:
      - "eureka:eureka"
      - "user-mysql:user-mysql"
    depends_on:
      - "eureka"
      - "user-mysql"
  gateway:
    image: microservice/gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=default
    ports:
      - target: 8765
        published: 9002
        protocol: tcp
        mode: host
    restart: unless-stopped
    links:
      - "eureka:eureka"
    depends_on:
      - "eureka"
